### ISSUE TITLE
Ask user to type password in terminal if none specified in config

### ISSUE THREAD

**Issue by detj** [leftshifters/upshift#12]
Need to see if we can get `xcpretty` to prompt for password directly if no master password specified in config. Would be convenient. Of course, this requires some level of support from `xcpretty` I guess.

Once I added masterPassword to config, xcpretty was automatically installed so that works! 👍 

@sudhanshuraheja Question

```
echo -ne ${masterPassword} | sudo -S gem install xcpretty
```

what does the `-e` flag do? I didn't find anything on this in `man echo`

**Comment by detj** [comment]
Actually, the auto `xcpretty` install did not work. Got an error in the next step saying xcpretty is not installed.

_Update: Added #13_

**Comment by detj** [comment]
> Need to see if we can get xcpretty to prompt for password directly if no master password specified in config. Would be convenient. Of course, this requires some level of support from xcpretty I guess.

Tested this out. sudo automatically asks for the password. For automated environments, password has to be read from config.ci

**Comment by sudhanshuraheja** [comment]
This has been added, will be there is 0.6.6
