### ISSUE TITLE
Instruments complaining that template is not specified

### ISSUE THREAD

**Issue by detj** [leftshifters/upshift#17]
The exact error.

```
Instruments Usage Error: No template (-t) specified
```

Though, the compile and build was successful despite this warning. Does instruments expect template to be present always? Should we set the Blank template as default?

https://developer.apple.com/library/tvos/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/ProfilingTemplates.html

**Comment by sudhanshuraheja** [comment]
I ignored this and just hid it under the rug :)

This is because I wasn't sure if we can set a blank template and I didn't really understand what a template does. 

Can you please add in a blank template and send a PR @detj

**Comment by detj** [comment]
Okay. I'm not sure either if we need to specify a template. I will test with a blank template and see how it goes.

**Comment by sudhanshuraheja** [comment]
Done.
